version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    networks:
      - mern_network
    environment:
      GEMINI_API_KEY: AIzaSyAjLTI4QqUHI8xQxo1pZR9oUi4fuc4nBVk
      MONGO_URL: mongodb+srv://Education:12345@education.ze0j7u7.mongodb.net/?retryWrites=true&w=majority&appName=Education
      JWT_SECRET: education
      YOUTUBE_API_KEY: AIzaSyBfsjZlMszqxl4V8PEBq9mpBBd8_80JfLQ
      GOOGLE_KEY: 5f73e414a92036c04fcbd105509dc6e42c31e3745f0f3fd2dea160e003ce91c3 
    volumes:
      - ./Backend:/app
      - /app/node_modules   # Prevent overwriting node_modules inside container
    restart: unless-stopped

  frontend:
    build: ./Frontend
    ports:
      - "8080:8080"
    networks:
      - mern_network
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_ML_URL: http://localhost:8000
      VITE_ZEGO_APP_ID: 1993186722
      VITE_ZEGO_SERVER_SECRET: "29eb815e6fa2cf1540af55fafd010d13"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    restart: unless-stopped
   
  python:
    build: ./ML
    ports:
      - "8000:8000"  # Flask app listens on 8000
    networks:
      - mern_network
    environment:
      GEMINI_API_KEY: AIzaSyAjLTI4QqUHI8xQxo1pZR9oUi4fuc4nBVk
      MONGO_URL: mongodb+srv://Education:12345@education.ze0j7u7.mongodb.net/?retryWrites=true&w=majority&appName=Education
      JWT_SECRET: education
      YOUTUBE_API_KEY: AIzaSyBfsjZlMszqxl4V8PEBq9mpBBd8_80JfLQ
    volumes:
      - ./ML:/app
    restart: unless-stopped

networks:
  mern_network:
    driver: bridge
